"""常量定义：版本、默认值、枚举字符串等"""

# 默认值
DEFAULT_STRATEGY = "silence"
DEFAULT_MIN_SILENCE_SEC = 0.35
DEFAULT_SILENCE_THRESHOLD_DB = -35.0
DEFAULT_MIN_SEG_SEC = 1.0
DEFAULT_MAX_SEG_SEC = 25.0
DEFAULT_PAD_SEC = 0.10
DEFAULT_JOBS = 1
DEFAULT_LOG_LEVEL = "INFO"

# 策略枚举
STRATEGY_CHOICES = ["silence", "energy", "vad"]

# VAD 策略默认值
DEFAULT_VAD_AGGRESSIVENESS = 2
DEFAULT_VAD_FRAME_MS = 30
DEFAULT_VAD_SAMPLE_RATE = 16000
DEFAULT_VAD_MIN_SPEECH_SEC = 0.20

# Auto-strategy 默认值
DEFAULT_AUTO_STRATEGY_ORDER = "silence,vad,energy"
DEFAULT_AUTO_STRATEGY_MIN_SEGMENTS = 2
DEFAULT_AUTO_STRATEGY_MIN_SPEECH_TOTAL_SEC = 3.0
DEFAULT_AUTO_STRATEGY_MAX_SPEECH_RATIO = 0.98  # 如果 speech_total_sec / duration >= 0.98，认为覆盖几乎全长

